model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4
    litellm_params:
      model: gpt-4
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4o
    litellm_params:
      model: gpt-4o
      api_key: os.environ/OPENAI_API_KEY

litellm_settings:
  # set_verbose: True  # Uncomment this if you want to see verbose logs; not recommended in production
  drop_params: True
  enable_json_schema_validation: True
  num_retries: 5
  request_timeout: 600
  telemetry: False

general_settings: 
  master_key: os.environ/LITELLM_MASTER_KEY # CRITICAL: Use environment variable
  store_model_in_db: True
  database_url: os.environ/DATABASE_URL # CRITICAL: Database connection
  database_connection_pool_limit: 3 # Reduced to avoid connection limits