services:
  - type: web
    name: litellm-proxy
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        sync: false  # Set this in Render dashboard as environment variable
      - key: LITELLM_MASTER_KEY
        sync: false  # Set this in Render dashboard as environment variable
      - key: STORE_MODEL_IN_DB
        value: "True"
      - key: DISABLE_SCHEMA_UPDATE
        value: "false"  # Enable database migrations
      - key: USE_PRISMA_MIGRATE
        value: "false"   # Use db push instead of migrations
    numInstances: 1
    healthCheckPath: /health/liveliness
    autoDeploy: true
